GET http://localhost:3000/users 
###

POST http://localhost:3000/profile/journal
content-type: application/json

{
    "title": "Something",
    "date": 10102000,
    "content": "Lorem Ipsum"
}

###

DELETE  http://localhost:3000/profile/journal/4

###
PUT http://localhost:3000/profile/journal/2
content-type: application/json

{
    "title": "Something",
    "date": 10102000,
    "content": "Lorem Ipsum"
}